### ISSUE TITLE
[TF2GM] Bot code requires rewrite due to the amount of lag and CPU usage

### ISSUE THREAD

**Issue by Seamusmario** [LeadKiller/leadbot#11]
Compared to the dev build of Civilian 2, Civilian 2 has made CTFBots obsolete due to the fact how the bot code was merged in, The bots causes more lag than the latest build of leadbot. I had to split the ctfbots code and downloaded Leadbot it in a separate addon.

With the amount of errors (& lag), MvM is unplayable at this point. We had to use Nextbot NPCs to make actual waves.

**Comment by LeadKiller** [comment]
The bot code is being redone with proper timers and better interpolation in the beta version.
Gamemode support will be also redone for most gamemodes such as TF2 Gamemode and nZombies.
During the next few days, the beta milestone will be updated with full issues that explain how the beta will work.

If you need fake players for something like TF2 MVM, I would highly recommend [Team Fortress 2 Bots](https://steamcommunity.com/sharedfiles/filedetails/?id=352877666) as they are nextbots rather than player bots.

**Comment by Seamusmario** [comment]
> If you need fake players for something like TF2 MVM, I would highly recommend Team Fortress 2 Bots as they are nextbots rather than player bots.

Exactly what we've used.

**Comment by LeadKiller** [comment]
Fixed with https://github.com/LeadKiller/leadbot/commit/ff53def57c70c3c556615807b68cee50ff653add and https://github.com/Moddage/TF2-Gamemode/commit/aa04b3a85432494b289e57cff53cd10f0e3b7d34.
